### ISSUE TITLE
tips - avoiding pixelation during rotation of objects?

### ISSUE THREAD

**Issue by lessw2020** [Unity-Technologies/com.unity.perception#157]
Are there any tips or recommendations on how to avoid pixelation during rotation of the objects?  I am running in HDRP and generating high res but I see a lot of jagged pixelations on my objects. The effect is reduced with higher res finished images, but seems I must have something wrong.  
![pixelation](https://user-images.githubusercontent.com/46302957/105399889-10a1c480-5bd9-11eb-8d22-c8685c3adff3.JPG)

I don't see these in the samples objects, but not clear what the fix is.  Our models are high_res and look great in normal viewing.
Here's an example of the issue:

**Comment by mkamalza** [comment]
The jagged edges you see here are due to aliasing, which happens when slanting lines are rasterized to the 2D pixel grid your images are rendered on. You can try a variety of anti-aliasing options in the HDRP pipeline. Please visit this page for a comprehensive overview:

https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@7.1/manual/Anti-Aliasing.html

**Comment by lessw2020** [comment]
Hi @mkamalza  - thanks a bunch!  I tested some configs and subpixel morphological aa works best.  Greatly appreciate the link and info!
![subpixel_aa](https://user-images.githubusercontent.com/46302957/105413217-a72ab180-5bea-11eb-9d48-a90773c61d6b.JPG)

**Comment by mkamalza** [comment]
Cool, glad you found a solution!
