### ISSUE TITLE
outer bbox on objects is deficient under rotation (cover 80%, not 100%)

### ISSUE THREAD

**Issue by lessw2020** [Unity-Technologies/com.unity.perception#217]
I've been closely reviewing the bboxes for our datasets and have noticed that the outermost bounding box is consistently coming up short when the object is heavily rotated. 
*I'm using invisible geometry labelling.  The invisible labels (sub-components) remain accurate.  It's the prefab itself that is coming up short. 
Here it is with no rotation:
![correct_labelling](https://user-images.githubusercontent.com/46302957/108785797-fb48ee80-7526-11eb-8f8e-25a9d8545ca4.JPG)

Here it is at extreme (45 degree) rotation.  If you look at the green outer box (the prefab object itself) then I've highlighted the difference of it vs the bottom label.  It should be at the same width/height of the bottom box to be accurate:
![rotated_miss](https://user-images.githubusercontent.com/46302957/108785864-24697f00-7527-11eb-84fb-5d0b3d49a9e7.JPG)

Another example:
![rotated_miss_2](https://user-images.githubusercontent.com/46302957/108785872-2cc1ba00-7527-11eb-9be6-cda7338df9dc.JPG)

The discrepancy is reduced as rotation drops away from 45 degrees:
![slight_miss](https://user-images.githubusercontent.com/46302957/108785896-3d723000-7527-11eb-9fd9-2204235c8f31.JPG)

Any ideas on how to correct?  For now I will synthetise the outer box by building it from the top and bottom boxes which so far appear to remain accurate.
Note - one idea, I'm rescaling the items randomly.  Not sure if that impacts, but as noted it appears correct for non-rotated, and then degrades and peaks at 45 degrees rotation.
Thanks!

**Comment by mkamalza** [comment]
So my hunch is that in the frames where the green box is only partially bounding the main parent object, the `Bottom_accula` object is fully "hiding" the parent object from the camera's view. If no pixels of `rdt_accula` are visible beyond the overlaying `Bottom_accula` section, that whole section will essentially be cut off from the `rdt_accula` object.

I am not clear why rotations would affect this though. Perhaps the object is also rotating slight around its own height axis and that causes the discrepancy between different rotations? 

What I suggest is you make the quad labeled `Bottom_accula` a little bit smaller so that it is always engulfed by the main object. Then run your simulation again and see if things improve.

**Comment by lessw2020** [comment]
Hi @mkamalza  - you solved it :) 

I brought the sub component dimensions in, to be just within the prefab itself, and now the labelling is as expected.  
Note for reference, I had assumed that since the material of the labels is transparent it would see through it for the labelling as well.
Anyway, that resolves this issue and will keep the inner labels 'contained' within the prefab. 
Thanks for the fast response!
![fixed_outer_rdt](https://user-images.githubusercontent.com/46302957/108791098-23d6e580-7533-11eb-9268-8ae651c7d46b.JPG)

**Comment by mkamalza** [comment]
Great. I'm glad it's working now! In the near future, we will be adding the ability to do this type of thing with two separate bounding box 2D labelers on the same camera, using different label configs. E.g. one config would include `rdt_accula` and the other `Bottom_accula`. This way, you will able to set any size for `Bottom_accula` without having it hide the main object from the labeler that is looking for it.

This will require some upgrades to our label matching code though, so it does not work with the current implementation.
