### ISSUE TITLE
How to adjust the background to make it clean and organized?

### ISSUE THREAD

**Issue by arjunrao796123** [Unity-Technologies/com.unity.perception#222]
The background is a little too random and unstructured when I am trying to create it. Is there any way I can order the objects that are being generated in the background?
Suppose you want to create randomized but organized sets of environments, how do you go about doing that?

Thank you in advance.

**Comment by arjunrao796123** [comment]
Suppose you want to create randomized sets of environments, how do you go about doing that?

**Comment by mkamalza** [comment]
Hi,

The background placement Randomizer included with the Perception package uses Poisson disk sampling to select random positions within a given area. In order to make this process more organized, you can modify the corresponding part of the code to have it sample positions in a different manner. To do this, you would first need to create new background randomizer by copying the code that's already there into a new C# class in your own project. Just make sure to change the class name and it's title in the Add Randomizer menu (defined at the top) so that they are different from the stock class.

The part of the code responsible for position sampling and object placement is this:

```C#
protected override void OnIterationStart()
        {
            for (var i = 0; i < layerCount; i++)
            {
                var seed = SamplerState.NextRandomState();
                var placementSamples = PoissonDiskSampling.GenerateSamples(
                    placementArea.x, placementArea.y, separationDistance, seed);
                var offset = new Vector3(placementArea.x, placementArea.y, 0f) * -0.5f;
                foreach (var sample in placementSamples)
                {
                    var instance = m_GameObjectOneWayCache.GetOrInstantiate(prefabs.Sample());
                    instance.transform.position = new Vector3(sample.x, sample.y, separationDistance * i + depth) + offset;
                }
                placementSamples.Dispose();
            }
        }
```

Specifically, the lines that sample positions are#223 
```C#
var placementSamples = PoissonDiskSampling.GenerateSamples(
                    placementArea.x, placementArea.y, separationDistance, seed);
```

One thing you could do is to change those lines to have them output a specific order of positions within `placementArea`.

Alternately, you could also create complete backgrounds, save them as prefabs, and feed those into the background placement randomizer. With this approach, the background placement randomizer would just have to pick one of your pre-made backgrounds and instantiate it at the same position on each frame. Therefore, the position sampling code would be removed and the position would always be constant.

Let me know if that helps.

**Comment by arjunrao796123** [comment]
Thank you for the quick response. I'll try this and get back to you.

**Comment by arjunrao796123** [comment]
> Hi,
> 
> The background placement Randomizer included with the Perception package uses Poisson disk sampling to select random positions within a given area. In order to make this process more organized, you can modify the corresponding part of the code to have it sample positions in a different manner. To do this, you would first need to create a new background randomizer by copying the code that's already there into a new C# class in your own project. The file is named `BackgroundObjectPlacementRandomizer.cs`. Just make sure to change the new class's name and title in the Add Randomizer menu (defined at the top) so that they are different from the stock class.
> 
> The part of the code responsible for position sampling and object placement is this:
> 
> ```cs
> protected override void OnIterationStart()
>         {
>             for (var i = 0; i < layerCount; i++)
>             {
>                 var seed = SamplerState.NextRandomState();
>                 var placementSamples = PoissonDiskSampling.GenerateSamples(
>                     placementArea.x, placementArea.y, separationDistance, seed);
>                 var offset = new Vector3(placementArea.x, placementArea.y, 0f) * -0.5f;
>                 foreach (var sample in placementSamples)
>                 {
>                     var instance = m_GameObjectOneWayCache.GetOrInstantiate(prefabs.Sample());
>                     instance.transform.position = new Vector3(sample.x, sample.y, separationDistance * i + depth) + offset;
>                 }
>                 placementSamples.Dispose();
>             }
>         }
> ```
> 
> Specifically, the lines that sample positions are:
> 
> ```cs
> var placementSamples = PoissonDiskSampling.GenerateSamples(
>                     placementArea.x, placementArea.y, separationDistance, seed);
> ```
> 
> One thing you could do is to change those lines to have them output a specific order of positions within `placementArea`.
> 
> Alternately, you could also create complete backgrounds, save them as prefabs, and feed those into the background placement randomizer. With this approach, the background placement randomizer would just have to pick one of your pre-made backgrounds and instantiate it at the same position on each frame. Therefore, the position sampling code would be removed and the position would always be constant.
> 
> Let me know if that helps.

This was really helpful. I am new to Unity and I was able to understand what is happening in a better manner.

**Comment by mkamalza** [comment]
Glad to know it helped. I will go ahead and close this issue for now. Feel free to open a new one in case there is anything else to discuss.
