### ISSUE TITLE
It is possible to capture frames only when something changes/moves in the frame?

### ISSUE THREAD

**Issue by Neurotaur** [Unity-Technologies/com.unity.perception#237]
Hi, 

Is there a configuration in perception camera to capture frames only when there's a change?  
For some projects, we want to capture and save frames only if there is a change in object position or camera rotation or if there's a change in the pose of objects with labels. If there is, we can reduce the number of redundant images files and have lower C02 footprint.

**Comment by mkamalza** [comment]
Hi, 

One thing you could try is the manual capture trigger mode. If you set the **Capture Trigger Mode** to `Manual` in your Perception Camera, it will only capture when you call its `RequestCapture` function. 
If you are using a Scenario to randomize your scene, make sure you allow at least one frame to render in each Iteration after calling the above function and before moving on to the next Iteration, so that the camera has time to capture.

**Comment by JonathanHUnity** [comment]
Closing this for now. Feel free to reopen if there are more issues.
