### ISSUE TITLE
How do I convert Unity image annotations into annotations usable for training an ML model?

### ISSUE THREAD

**Issue by Tylersuard** [Unity-Technologies/com.unity.perception#251]
Unity outputs the synthetic data and annotations, which is great, but there are no instructions for how to turn these annotations into something usable for training an object detection or semantic segmentation model.

**Comment by lessw2020** [comment]
You can use the converter tool I have published here:
https://github.com/lessw2020/perception_tools
![convert_complete](https://user-images.githubusercontent.com/46302957/111084321-014f4100-84cf-11eb-986f-306a27a3f470.JPG)


There is both a notebook and a script.  For the notebook run all the cells down to the begin processing. 
Set the path to the perception directory, adjust the image height and width and the output name if needed...and run. 
Will process and produce a training ready Coco format file for you. 

Note that this is for 2D bounding boxes.  I have not implemented segmentation yet.

**Comment by Tylersuard** [comment]
THANK YOU!!!

**Comment by Tylersuard** [comment]
Firs of all, THANK YOU!  
Second, I am running on Linux, getting this error consistently:
"directory of type Perception not found. aborting..."

In the instructions you refer to the "perception directory".  What do you mean by that?

**Comment by lessw2020** [comment]
Hi @Tylersuard:
Definitely welcome.
 'perception directory' should be the folder where Unity/perception puts it's three main output folders - Dataset*, Logs, and RGB*.
 The error is triggered if that path is not of type directory.  (are you passing in a path to the file instead of the directory?)
 
 Example from my drive (though this is windows):
 
![perception_directory](https://user-images.githubusercontent.com/46302957/111237066-7abf6000-85b1-11eb-9ce8-c236309a5b40.JPG)

Thus the 'perception_directory' is the full path to that highlighted dir, 26cd1c73-4631-4b67-bfb1-9726d23d8de6. 

From there, the converter will look for the first Dataset* folder and use that to get the annotations, and could also use the RGB folder if needed to check images/sizes, etc.

It should work fine on Linux, so if you can verify you are passing in path to the directory that should let you proceed.
If not, feel free to just post a screenshot of what you are passing in, and if can also update it to strip a filename and get the parent dir.

**Comment by JonathanHUnity** [comment]
Wonderful @lessw2020! 
For other types of models, we do provide the library [Dataset Insights](https://pypi.org/project/datasetinsights/), a python library for loading Perception-based datasets. This should make it straightforward to feed the data into your model training code.

**Comment by orangeRobot990** [comment]
did anyone try to use these annotations and register them into detectron2 models ? 
can we use directly like this
https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html#:~:text=from%20detectron2.data.datasets%20import%20register_coco_instances%0Aregister_coco_instances(%22my_dataset%22%2C%20%7B%7D%2C%20%22json_annotation.json%22%2C%20%22path/to/image/dir%22)
```
from detectron2.data.datasets import register_coco_instances
register_coco_instances("my_dataset", {}, "json_annotation.json", "path/to/image/dir")
```

thank you @lessw2020 for providing your code, ill try it soon !

**Comment by lessw2020** [comment]
Hi @orangeRobot990 - I didn't use synthetic inside of detectron2, but have worked with detectron2 beyond that, and would say it should work fine to import the synthetic with coco annotations.
Once the synthetic images are annotated with coco format like I setup, they will work anywhere coco labelling is accepted. 

Hope that helps!
Less
