### ISSUE TITLE
human pose estimation

### ISSUE THREAD

**Issue by soans1994** [Unity-Technologies/com.unity.perception#283]
Hello again, 

I have some queries regarding the human pose estimation keypoints extraction. 
1. The skeleton objects under the player model are the keypoints we extract. Are those the same objects responsible for the movement of the 3d model? 
2. How to change the camera view, or should i use randomizer option to change the orientation of the model.
3. I want to create a simple 3d mesh of a sleeping person, how can i perform this?

**Comment by mkamalza** [comment]
Hi,

1. Yes, the joints are responsible for animating the object since the animation clip that you use looks for those joints in the model.
2. You could create a custom Randomizer to change the location of your camera on each iteration. To learn how to create a custom Randomizer, I recommend following the [Perception Tutorial](https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Documentation~/Tutorial/TUTORIAL.md), especially its [second phase](https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Documentation%7E/Tutorial/Phase2.md).
3. For this you would need to pose a rigged human model into a sleeping pose and bake this pose into the mesh. You could also look for ready-made sleeping animations in online content libraries, such as [Maximo](https://www.mixamo.com/#/).

**Comment by soans1994** [comment]
@mkamalza Thank you for your solution, I will check out the solutions.

**Comment by soans1994** [comment]
@mkamalza Thank you for the reply, i will check out the solutions.

**Comment by soans1994** [comment]
@mkamalza

 I want to create a new animation for the human model, can you give me links for the tutorial. Also i checked the default animation files in the human pose perception package. The inspector window has model, rig, animation, materials options. Can i acheive different animations by editing these parameters? How can i view the joints responsible for the animation?

**Comment by mkamalza** [comment]
The actual animation clips cannot be modified inside of Unity. Creating and modifying animations is typically done using 3D content authoring software such as Maya.

**Comment by litchiar** [comment]
Hello,I have a question. Since building a human pose estimation dataset is really expensive and the most used datasets were made by unversities and companies using professional equipments,iIs the dataset obtained using the virtual scene valid in the real environment?

**Comment by JonathanHUnity** [comment]
@litchiar This is a fantastic question! We have seen success in various tasks with synthetic data and believe that synthetic keypoint data will be useful for real-world applications, but exactly how much is an open question. Here is a recent blog post discussing some related applications with numbers showing sim2real: https://blogs.unity3d.com/2021/04/09/boosting-computer-vision-performance-with-synthetic-data/

**Comment by JonathanHUnity** [comment]
Closing this for now!

**Comment by JonathanHUnity** [comment]
Btw, @litchiar and @soans1994, these are great questions for our newly-minted [Computer Vision Unity Forum](https://forum.unity.com/forums/computer-vision.626/). Hope to see you on there.
