### ISSUE TITLE
Some questions on foreground object placement

### ISSUE THREAD

**Issue by TalalWasim** [Unity-Technologies/com.unity.perception#291]
Hello,

I have just started using the perception package and have a couple of questions regarding the foreground object placement. Currently, from what I understand, one can define a placement area along the x and y axes and place at a fixed depth. Is it possible to have varying depth as well?

Furthermore, for my specific scenario, I have a background scene and need to place objects such that they are exactly on the ground. For example, I have a road and need the cars to be placed on the road (and not have it flying around in the air). So a sort of restriction on the y-axis I believe. Is that possible to do?

Finally, is there a way to restrict the number of objects placed in the scene? Like if I want exactly 5? or a maximum of 5?

Thanks in advance and apologies if these are very basic questions. I am new to unity and c#

**Comment by sleal-unity** [comment]
Hi @TalalWasim!

So to summary my answer to all these questions, yes! Each of these randomizations is possible, but I don't think any of these behaviors are supported out of the box. So what you would need is some custom randomizers to solve these problems. [Here is a doc](https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Documentation%7E/Randomization/Randomizers.md) that should help with the basics of writing your own randomizers. I would also recommend exploring the [existing example randomizers](https://github.com/Unity-Technologies/com.unity.perception/tree/master/com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers) provided with the package to get a better feel for how randomizers can be implemented.

For your first question, I would recommend using a FloatParameter to define a sample range for the random depth behavior you are describing. So in your custom randomizer, you can essentially copy the existing [ForegroundObjectPlacementRandomizer](https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/ForegroundObjectPlacementRandomizer.cs) code and sample this depth range parameter to determine the z-coordinate of each placed object.

Your second question is more context specific. Again, we don't have any randomizers that could randomize car positions out of the box, but a custom randomizer could be written to specify the ground region you want to place cars in and how far apart you need cars to be. I'd recommend taking a look at the the [Poisson disk sampling utility](https://github.com/Unity-Technologies/com.unity.perception/blob/master/com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Utilities/PoissonDiskSampling.cs) included in the package to see if this algorithm would be sufficient for your needs or if you have a different set of placement constraints in mind.

Lastly, yes, there is a way to write a custom randomizer that restricts the number of objects placed in the scene (if we're talking about foreground randomization). The existing foreground randomizer is tailored more for filling a 2D space with objects and therefore does not have this max objects parameter by default, but it could be implemented with some minor tweaks. First, I would recommend adding a FloatParameter for specifying the sample range of the number of objects you want placed in the scene. Then, in the actual object spawning portion of the code, instead of instantiating an object for each viable poisson point, I would randomly choose the first X number of generated poisson points to place objects at based on the sampled number of objects meant to be placed in the given scenario iteration.

Hopefully this advice helps point you in the right direction! Feel free to ping this thread if you have any other questions!

**Comment by TalalWasim** [comment]
Hey,

Thank you so much. I have been able to add some of the features (both the bound on the number of objects and also the varying depth).

But I had one more question. In the foregroundObjectPlacement Randomizer, there is an "offest" that is being added to the sample position generated by the PoissonDiskSampling positions

`var offset = new Vector3(placementArea.x, placementArea.y, 0f) * -0.5f;`

I am not sure why this is being used. Is it to center the X-Y plane around the origin? Or is it something else?

**Comment by JonathanHUnity** [comment]
Yes, this is to center the objects on the origin.
Closing this for now, but feel free to comment again with more questions. By the way, this is a great discussion for our newly minted [Computer Vision Unity Forum](https://forum.unity.com/forums/computer-vision.626/). Hope to see you there.
