### ISSUE TITLE
Post process volume does not affect perception captures

### ISSUE THREAD

**Issue by ComeOnAndSam** [Unity-Technologies/com.unity.perception#342]
I was adding post process effects with a volume because I wanted to change the look of my captures, but then I check the RGB output and it was missing all the volume's post processing effects entirely. It really limits how you can affect your captures if there's no way around that.

**Comment by mkamalza** [comment]
Hi,

This issue is now fixed on the master branch by using an updated version of the capture package dependency (com.unity.simulation.capture). A new patch will be released soon that will include this fix. In the meantime, you could either use the master branch (by cloning the repo and then adding the package from disk in Unity), or manually update the capture dependency in your Unity project's manifest to the version used in master (0.0.10-preview.22).

**Comment by ComeOnAndSam** [comment]
Yep, that fixed it, thanks!
