### ISSUE TITLE
All RGB Images are blank

### ISSUE THREAD

**Issue by vaibhavbagri** [Unity-Technologies/com.unity.perception#346]
Hi, I'm using the latest version of the repository (com.unity.perception@0.8.0-preview.4). I followed all the steps in the tutorial, but on hitting play, all the RGB images that are generated are blank. The surprising part is that the corresponding segmentation is being generated properly. I'm not exactly sure what is the issue.

Device specifications - MacBook Pro running macOS Big Sur 11.2.3
Unity Version - 2020.3.12f1

Attaching below a sample of the RGB and corresponding segmentation file:

![rgb_8](https://user-images.githubusercontent.com/32847060/125004830-9397c980-e017-11eb-898e-e3c5ec95f738.png)
![segmentation_8](https://user-images.githubusercontent.com/32847060/125004836-985c7d80-e017-11eb-85a5-92604989ec9d.png)

Would greatly appreciate if you could help me out with this. Thanks!

**Comment by mkamalza** [comment]
Hi, thank you for bringing this to our attention. It turns out this is a bug with the latest capture package that we use. This seems to only happen in OSX and when MSAA is enabled on the camera. As a workaround, try setting MSAA to off in the Camera component of the camera gameobject. As an alternative for anti aliasing, you could use FXAA.
