### ISSUE TITLE
Question: Saving multiple variants of a single simulation iteration

### ISSUE THREAD

**Issue by umairkhawaja** [Unity-Technologies/com.unity.perception#352]
I wanted to know if its possible to get the following functionality:
Whenever an iteration is generated and all randomizers have produced a single frame, is it possible to edit objects active in that frame and save the modified image along with its updated labels?

**Comment by StevenBorkman** [comment]
If I understand your question correctly then yes. The 'Fixed Length Scenario' has attributes on it that you can set so that the simulation runs a number of frames before it re-randomizes the scene. In this example I am using the foreground randomizer to place create cubes and each cube has a simple script attached to it to rotate it.

Here is what the final scene looks like:
![rotate_demo](https://user-images.githubusercontent.com/66975693/127657916-70a1ac44-8cd5-460d-83a2-93928f72ea6c.gif)

Here is what my scenario looks like, the important field is the 'Frames Per Iteration' field, in mine I have it set to 20.
![image](https://user-images.githubusercontent.com/66975693/127657971-b088e3dc-105a-4eee-821f-c2535bb84795.png)

And finally this is what my rotator script looks like:
`using UnityEngine;

public class RotateMe : MonoBehaviour
{
    public float rotateAmount;

    // Update is called once per frame
    void Update()
    {
        transform.localRotation *= Quaternion.Euler(0, rotateAmount, 0);
    }
}`

**Comment by umairkhawaja** [comment]
Yes I'm aware of the frames per iteration feature, can I modify objects active in the scene for each frame though?

An example:
I have a humanoid wearing a jacket, a hat, and pants. 
I have other randomizers which randomize the pose and other attributes of this humanoid.
Now, for each image that results as a product of these randomizers:
 1) I want to remove the hat only, while keeping everything else constant and then save this frame along with its annotations using labelers
 2) I want to remove the jacket only, while keeping everything else consant
 3) So on and so forth
 
Is this possbile?

**Comment by StevenBorkman** [comment]
Yes, this is possible but you will have to modify some randomizer scripts.  This is what my final product looks like:
![human_color_change](https://user-images.githubusercontent.com/66975693/127675849-517a8ca3-e107-42de-aa82-1ed3600f4b68.gif)

I did this by modifying the AnimationRandomizer script to:

1.  Have a framePause of 10 frames meaning that this randomizer will only execute once every 10 frames, I did that by adding this line to the file:
`if (count++ % framePause != 0) return;`
where count is a private int that increments each frame, and framePause holds the value that you want to pause at

2. added a line pause the animation so that it doesn't keep playing after choosing a new animation:
`animator.speed = 0;`

3. Just added the ColorRandomizer (with no modifications to my scenario) and added the ColorRandomizerTag to by model

Full modified AnimationRandomizer.cs script:
`using System;
using UnityEngine;
using UnityEngine.Perception.Randomization.Parameters;
using UnityEngine.Perception.Randomization.Randomizers.SampleRandomizers.Tags;
using UnityEngine.Perception.Randomization.Samplers;

namespace UnityEngine.Perception.Randomization.Randomizers.SampleRandomizers
{
    /// <summary>
    /// Chooses a random of frame of a random clip for a game object
    /// </summary>
    [Serializable]
    [AddRandomizerMenu("Perception/Animation Randomizer")]
    public class AnimationRandomizer : Randomizer
    {
        FloatParameter m_FloatParameter = new FloatParameter{ value = new UniformSampler(0, 1) };

        const string k_ClipName = "PlayerIdle";
        const string k_StateName = "Base Layer.RandomState";

        public int framePause = 10;
        int count = 0;

        void RandomizeAnimation(AnimationRandomizerTag tag)
        {
            if (!tag.gameObject.activeInHierarchy)
                return;

            var animator = tag.gameObject.GetComponent<Animator>();
            animator.applyRootMotion = tag.applyRootMotion;

            var overrider = tag.animatorOverrideController;
            if (overrider != null && tag.animationClips.GetCategoryCount() > 0)
            {
                overrider[k_ClipName] = tag.animationClips.Sample();
                animator.Play(k_StateName, 0, m_FloatParameter.Sample());
                animator.speed = 0;
            }
        }

        /// <inheritdoc/>
        protected override void OnIterationStart()
        {
            if (count++ % framePause != 0) return;

            if (m_FloatParameter == null) m_FloatParameter = new FloatParameter{ value = new UniformSampler(0, 1) };

            var taggedObjects = tagManager.Query<AnimationRandomizerTag>();
            foreach (var taggedObject in taggedObjects)
            {
                RandomizeAnimation(taggedObject);
            }
        }
    }
}
`

Hope this helps.

**Comment by umairkhawaja** [comment]
Thanks!

**Comment by StevenBorkman** [comment]
I'm going to mark this issue as resolved. Please re-open if you need more help.
