### ISSUE TITLE
Bounding box occluded parts

### ISSUE THREAD

**Issue by esgnn** [Unity-Technologies/com.unity.perception#401]
Hey there,
Is there an option to get bounding boxes that span also the occluded areas of an object (blue box in the image)? 
[https://imgur.com/a/dgCbgDL](url)

**Comment by aryan-mann** [comment]
Hi @esgnn 👋 ! 
We presently do not have out-of-box support for this particular use-case of 2D Bounding Boxes in the Perception package. 

Would love to hear more about how this feature would be useful to your project!

Best,
Aryan

**Comment by esgnn** [comment]
Hi @aryan-mann ,

I am building a generator for someone else, and she asked to have it as an option. 
One semi related follow up question then, do bounding boxes generated based on segmentation masks? The reason I am asking is, when a model has small imperfections, like very small gaps between two meshes,  it lets couple of pixels of another class (which is completely occluded) on the segmentation mask. Then I suspect, those pixels get registered as a visible part of an object and a bounding box is logged.  (if it is necessary, I can open another issue for this one)

**Comment by StevenBorkman** [comment]
Just to go into a little more detail to @aryan-mann answer, we do not have out-of-box support for this use case, but writing a custom labeler to get this solution is entirely possible. The 2D bounding box labeler uses the results of our rendered object shader to determine the visible parts of a labeled asset. So the answer to @esgnn most recent question is yes, you will get a bounding box for something as small as a single visible pixel.

The 3D bounding box labeler, on the other hand, determines the bounding box on an asset in 3D space, so this is non-shader based. Because of this it includes the occluded area of the labeled asset. To calculate the 2D bounds of the object, you could project all 8 corners of the 3D bounding box into screen coordinates, using Camera.ToWorldScreenPoint, and determine the overall 2D bounds.

**Comment by esgnn** [comment]
@StevenBorkman thank you for the extra information.
Regarding 3D box to 2D box, wouldn't it create a loose 2D bounding box for certain perspectives?
Ex: https://imgur.com/a/Odf4Wwl from https://arxiv.org/abs/1905.07754

**Comment by StevenBorkman** [comment]
@esgnn our 3D bounding boxes are calculated from the perspective of the main camera and we calculate really tight bounding boxes, so I don't think that you would see the loose bounding boxes as shown above

**Comment by esgnn** [comment]
@StevenBorkman I may be getting it all wrong. I understand that we can convert 3D bbox corners' min/max's to 2D. And if we count a tightly fit box collider is a 3D bbox. Then, I think in some perspectives bbox size would be wrong. 
ex: https://imgur.com/a/Y2ffYru

**Comment by StevenBorkman** [comment]
@esgnn No, it turns out I was the one getting it all wrong, you are correct, you will probably get loose bounding boxes going this route. Sorry

**Comment by esgnn** [comment]
Oh, thanks for the elaboration.
