### ISSUE TITLE
Question: I am looking to make a new randomizer that takes an input from the inspector tab in Unity, and creates that many objects

### ISSUE THREAD

**Issue by cd25643** [Unity-Technologies/com.unity.perception#436]
My current script generates 5 objects in a random location, rotation, and scale. I want to create a new input that is "amount". So say, in each frame I am generating 5 (whatever amount the user enters) of the same object, but all with random location/rotation/scale. At the end of each frame (capture) I want to delete the previous generated objects, and generate a new set of randomized objects. Below is my code that I have so far... Any suggestions?

```
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Perception.Randomization.Parameters;
using UnityEngine.Perception.Randomization.Randomizers;

[Serializable]
[AddRandomizerMenu("Object Placement Randomizer")]
public class DicePlacementRandomizer : Randomizer
{
    public FloatParameter ObjectScale;
    public Vector3Parameter placementLocation;
    public Vector3Parameter ObjectRotation;
    public FloatParameter ObjectAmount;

    public GameObjectParameter prefabs;

    private GameObject currentInstance;


    protected override void OnIterationStart()
    {
        int counter = Vector3.one * ObjectAmount.Sample();
        
        for (int i = 0; i < 5; i++)
        {

            currentInstance.transform.position = placementLocation.Sample();
            currentInstance.transform.rotation = Quaternion.Euler(ObjectRotation.Sample());
            currentInstance.transform.localScale = Vector3.one * ObjectScale.Sample();

        }

    }


    protected override void OnIterationEnd()
    {
        GameObject.Destroy(currentInstance);
    }
```

    
}

**Comment by RuiyuZ** [comment]
Hi @cd25643, I think you are on the right track, have you looked at the [ForegroundObjectPlacementRandomizer.cs](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Runtime/Randomization/Randomizers/RandomizerExamples/Randomizers/ForegroundObjectPlacementRandomizer.cs) file? I think you can do something very similar to it, instead of having a list of Prefabs to be placed by this Randomizer, you can just have 1 prefab and run it for 5 times like you did in the for loop
