### ISSUE TITLE
Removing Semantic Segmentation Annotations from Capture .json Files

### ISSUE THREAD

**Issue by XarisGeorgiadis** [Unity-Technologies/com.unity.perception#437]
Hello,

I have been trying for a few days to remove the Semantic Segmentation annotations from the capture .json files, since I do not need them in my capture data but I have not succeeded yet.

The annotations I am referring to are located in every capture_xyz.json file and look like:
 ```
       {
          "id": "e26f584b-e60d-45e7-b635-220032ab7cbf",
          "annotation_definition": "12f94d8d-5425-4deb-9b21-5e53ad957d66",
          "filename": "SemanticSegmentation/semantic_.png"
        }
```
I only want to remove these annotations and not modify the annotation_definitions.json file at all.

Can anyone point me to the file/line of code that I have to modify/remove in order to achieve this?

**Comment by XarisGeorgiadis** [comment]
As a follow-up question, is there a way to capture label data for the SemanticSegmentationLabeler in a similar way to how data from other labels are captured?

For example, 2D Bounding Box data are saved in the captures_xyz.json files as following:
```
     "annotations": [
        {
          "id": "43377237-f522-407a-9daf-51c434cf41d0",
          "annotation_definition": "f9f22e05-443f-4602-a422-ebe4ea9b55cb",
          "values": [
            {
  "label_id": 25,
  "label_name": "ceiling",
  "instance_id": 10,
  "x": 0.0,
  "y": 0.0,
  "width": 813.0,
  "height": 172.0
}
```
Is there a way to capture label data for the SemanticSegmentationLabeler in such a way?
For example:
```
     "annotations": [
        {
          "id": "3ae1cce5-3af1-45c2-9cf5-d5e31506c6e6",
          "annotation_definition": "12f94d8d-5425-4deb-9b21-5e53ad957d66",
          "values": [
            {
  "label_id": 25,
  "label_name": "ceiling",
   "pixel_value": {
            "r": 0.31372550129890442,
            "g": 0.125490203499794,
            "b": 0.0313725508749485,
            "a": 1.0
          }
}
```

**Comment by mkamalza** [comment]
Hi Xaris,

Regarding your first question, do you need the semantic segmentation ground truth at all? The point of that block of the json is to map each captured frame to a unique semantic segmentation image (png file) in the semantic segmentation folder. Therefore, if you do need this type of ground truth it would be reasonable to keep this block. If not though, you can just disable the whole labeler and therefore remove all of the output it generates (from you Perception Camera's list of labelers).

With this in mind, if you would still like to keep the labeler active and just remove that json block from the captures files (and keep the png images), you can comment this line from `SemanticSegmentationLabeler.cs`

`annotation.ReportFile(datasetRelativePath);`

As for a way to capture the rgb values in the captures files instead of the annotation definitions file, these values are a characteristic of the labeler and do not change through-out the simulation, so they would be identical for all captures. This is why they are recorded in the annotation definitions file. If you need to attach them to each frame's json information, you would need to post process the dataset.

**Comment by XarisGeorgiadis** [comment]
@mkamalza Hello and thank you for your response. 

In my current project I have 4 active labelers, one of which is the semantic segmentation one. My aim is to remove only the 3 lines I mentioned, since they are not necessary for my project. I am also renaming the png images externally, so the line containing the filename of each image will be pointing to a non-existent image anyway.
Removing the line of code you mentioned resulted in 0 capture files being created which is not desirable since I still want the data from the other labelers.

As for my second question, I thought it could be helpful to store the segmentation rgb values in the capture files in order to have them contain info only for the labeled objects that were active in each capture frame. After a talk with my supervisor we deemed that not necessary and we are content with them being on the annotation definitions file.

**Comment by mkamalza** [comment]
Hi @XarisGeorgiadis. You are right. It turns out there is a couple more lines to comment for this to work. These are lines 227, 228, and 268:
```C#
if (!m_AsyncAnnotations.TryGetValue(frameCount, out var annotation))
                return;
```
and

```C#
m_AsyncAnnotations[Time.frameCount] = perceptionCamera.SensorHandle.ReportAnnotationAsync(m_SemanticSegmentationAnnotationDefinition);
```
Keep in mind that even though this seems to be working, we are modifying some of the logic that synchronizes capture jsons and images, so I can't say for sure that you won't run into issues later on. Perhaps running a post processing script that removes those pieces is a better solution for you.

**Comment by XarisGeorgiadis** [comment]
Hello @mkamalza 

Commenting these lines does work but yes, removing them using a post processing script does seem like a better and safer solution. I will try to do that.

In any case, thank you for your help!
