### ISSUE TITLE
Question: Is it possible to disable transparent material blocking detected objects?

### ISSUE THREAD

**Issue by cd25643** [Unity-Technologies/com.unity.perception#439]
I'm trying to put trees in my scene where I am detecting objects. When applying material to the trees (specifically the leaves), the transparent areas aren't actually transparent. This is because the mesh models of the trees have large solid shapes where the leaves are used, but those shapes entirely obstruct any detected object, instead of only the actual leaves obstructing and being able to see through the transparent sections. Is there any setting somewhere baked into the perception package to fix this issue? Or would I need to create a model that doesn't rely on transparent textures?

![TreeMesh_example](https://user-images.githubusercontent.com/100865605/158248799-5f3884ad-1c45-4d55-acf9-c42ec090e220.jpg)
![leaves_example](https://user-images.githubusercontent.com/100865605/158248804-3f8b0c02-f1ec-4813-945a-3d4b07d34341.jpg)
![leaves_transparent_example](https://user-images.githubusercontent.com/100865605/158248807-1827ed69-17e5-483b-97fa-961bb6651ad8.jpg)

**Comment by mkamalza** [comment]
Hi, this comes down to how the shaders that we use for instance and semantic segmentation treat transparency. The former is used by the instance segmentation labeler as well as the bounding box 2d labeler. The latter is only used for the semantic segmentation labeler. 

Currently there is no option built into the package to take transparency into account the way you need it; however, we do have a branch that acts in that way. The branch is named [segmentation_with_opacity](https://github.com/Unity-Technologies/com.unity.perception/tree/segmentation_with_opacity).

The main differences in this branch are in the files `InstanceSegmentation.shader`, `SemanticSegmentation.shader`, `InstanceSegmentationCrossPipelinePass.cs` and `SemanticSegmentationCrossPipelinePass.cs`. I recommend having a look at the source code to see how it is different from the main branch. Essentially, we pass the objects' texture to the shaders and whenever a vertex has a transparent color from the texture, we pass 0 instead of the label id of the object.

Keep in mind though that because we are using transparency shaders in this branch, you may see some abnormalities with Z ordering of objects that have a large depth (Z) in the rendered image. Sometimes when a deep object is partially occluded by another smaller object, the transparency ordering does not correctly detect its rendering order in the scene and this may result in all of the object being either occluded or not occluded in your segmentation image.

**Comment by cd25643** [comment]
Great, I will do a comparison of the seg-opacity branch and the main branch and move forward on that route. Thanks!
