### ISSUE TITLE
Keypoint label missing for another human model.

### ISSUE THREAD

**Issue by moonsh** [Unity-Technologies/com.unity.perception#461]
![image](https://user-images.githubusercontent.com/13994270/161125031-3fd2aecd-b212-46cf-afc9-55d5e82c5970.png)

I've tried a different humanoid model and tested the keypoint labels but it seems like it failed to label keypoint.
The right model is another humanoid model and the left model is from the tutorial.

Maybe this is fine ?

**Comment by csun** [comment]
Hey there - do all of your joints have a `JointLabel` component added to them? This is required for the labeler to properly find each joint. 

Secondly, for the model on the right, have you gone through [this process](https://docs.unity3d.com/Manual/ConfiguringtheAvatar.html) to associate its joints with a humanoid avatar? The keypoint template depends on that being properly configured in order to find the joints it needs to label. You can read a bit more about that [here](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/GroundTruth/KeypointLabeler.md).

Please let me know if either of these things help fix your issue. If you're still stuck, feel free to email your project to computer-vision@unity3d.com and I'll take a look at it.

**Comment by csun** [comment]
Sorry, my previous statement was incorrect. If you're using the COCO keypoint template like the one used in the tutorial, you should not need `JointLabel`s on all joints - just the ones that have not been set up with the avatar system. My previous question about associating the joints with an avatar still stands.
