### ISSUE TITLE
how to visualise the depth .exr 

### ISSUE THREAD

**Issue by mshooter** [Unity-Technologies/com.unity.perception#543]
Hi, 

how do I visualise the depth .exr properly? 
When I open it with photoshop it just shows a segmented object 

Thank you

**Comment by StevenBorkman** [comment]
Hey @mshooter, there are a couple of ways to look at the exr files created for depth that I can recommend.

On my macbook they just open, so I assume that you are not on mac or maybe I have installed an app to look at them that I don't remember.

On windows, you can use RenderDoc to visualize them, it is a free program that you can use to debug graphics frames. But since it works with a lot of HDR image types, it can open exr files.

You can use a free web utility, such as https://viewer.openhdr.org/

Or you can try out our new Voxel51 based viewer: https://github.com/Unity-Technologies/pysolotools-fiftyone (which can be installed with `pip install pysolotools-fiftyone` in a python environment). But if you are on windows you will need to do some extra install steps to be able to visualize exr files. The instructions can be found in the README of the github page.

I am going to close this now, but feel free to open it back up if you have any other questions.

Best of luck.

**Comment by mshooter** [comment]
Hi,
thank you for answering and giving my tips. 
I am on Windows. 
Mine still displays the object in red instead of a proper depth map. 
![depth_erro](https://user-images.githubusercontent.com/23126918/204753286-efc007d0-ae20-4a3a-971a-4e0994d154ac.png)

**Comment by StevenBorkman** [comment]
Correct, you just have to change the range. I should have mentioned that. I'm glad to hear that everything is working for you now.
