### ISSUE TITLE
Question: How to acces new randomiser script in simulation scenario?

### ISSUE THREAD

**Issue by elaborate-username** [Unity-Technologies/com.unity.perception#566]
I am following the tutorial part 2 and I created the MyLightRandomizer script in the assets folder. Now I don't know how to add it to the Simulation Scenario list of randomisers; it does not show when I click 'add randomiser'. How do I make it so that I can add it?

**Comment by mark1ng123** [comment]
Hey there i had the same problem when i was following the tutorial, in my case the problem was i didn't name the file right and didn't inherit properly:
1. check the class name for example: public class MyPlacementRandomizer : Randomizer
2. check if you added it to the menu like it says:
  *[Serializable] 
  *[AddRandomizerMenu("PlacementRandomizer")]
3. also follow the instructions as it says: "In the Project tab, right-click on the Assets folder and select Create → Perception → C# Randomizer and RandomizerTag. Name your new script file MyLightRandomizerTag.cs."

if you keep having trouble tag me and we will figure it out, also it will be easier to help if you screenshot or give a code snip for next time.
Mark

**Comment by elaborate-username** [comment]
Thank you, I must have made a mistake in the naming somewhere; it works now that I did it again extra carefully.
