### ISSUE TITLE
How to render objects using phong shader instead of depth map?

### ISSUE THREAD

**Issue by davidfant** [Unity-Technologies/com.unity.perception#571]
I'm using [Unity Perception](https://github.com/Unity-Technologies/com.unity.perception) and [Synthetic Humans](https://github.com/Unity-Technologies/com.unity.cv.synthetichumans) to generate renders of humans. Using the depth labeler I can get a depth map of the actual human being rendered.

How can I instead get this shaded something like this?
![image](https://user-images.githubusercontent.com/17096641/216198079-a7805210-736e-4b29-8ad5-e1d385e46801.png)

**Comment by csun** [comment]
Hey David - I think this is actually more of a synthetic humans question rather than a perception one. I'm going to close this issue for now. Could you please open a new one in the synthetic humans repo? Additionally, I could use some more info here:

1. Do you want all objects in the scene to be rendered with this material? Or just the body?
2. Follow-up: should the clothes /hair be rendered like this too?

I think the answer here may be similar to the answer I gave for your other question. Although now I'm unsure if you want clothes / hair to render at all or if you just want the bodies.
