### ISSUE TITLE
Depth Labeler doesn't work

### ISSUE THREAD

**Issue by WiktorLigeza** [Unity-Technologies/com.unity.perception#584]
### Discussed in https://github.com/Unity-Technologies/com.unity.perception/discussions/583

<div type='discussions-op-text'>

<sup>Originally posted by **WiktorLigeza** March 22, 2023</sup>
![image](https://user-images.githubusercontent.com/60184155/227006711-e43c8bb3-9fb2-4fdf-a9a3-3f696a36090f.png)

Hi, my depth labeler is not working. I am using the perception package 1.0.0 in HDRP project with tutorial files and a conveyor belt sample.
It produces flat red depth files (just like one on the screenshot). I mean the program runs but the results are, idk, flat(?).

PS: Unity Editor 2022.1.18f1
</div>

**Comment by StevenBorkman** [comment]
Hi, it's probably working correctly, it's just difficult to see the results because the data is encoded in 64 bits in the red channel and most image viewing applications only see 32 bits. Please see the [documentation ](https://github.com/Unity-Technologies/com.unity.perception/blob/main/com.unity.perception/Documentation~/PerceptionCamera.md#depth-labeler) on the depth labeler for some hints on how to view it properly.

Also, let me point out our Voxel51 integration, found [here](https://github.com/Unity-Technologies/pysolotools-fiftyone), which is a really good way to view perception generated data.

**Comment by WiktorLigeza** [comment]
Yeap, it works! Thanks for your quick response :D

**Comment by WiktorLigeza** [comment]
Hi, I have another problem. When reading an EXR file using cv2 in Python, the point cloud is smaller than it should be

`img = cv2.imread("test1.exr", cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH)`
# img dtype is float32

Is it possible that the camera settings in Unity may be contributing to this issue?

**Comment by lesreaper** [comment]
I'm running into the same issue, but I'm on Linux, and the `pysolotools-fiftyone` isn't installing properly. I'm using 32-bit GIMP, and it says the images are 32 bit. 

Are there any other options to view these on Linux?
